<robot name="payload" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name='robot_model' default='payload' />
    <xacro:arg name='robot_name' default='$(arg robot_model)' />
  
    <!-- Payload geometries -->
    <xacro:property name="payload_length" value="0.106" />
    <xacro:property name="payload_width" value="0.075" />
    <xacro:property name="payload_height" value="0.040" />
    <link name="$(arg robot_name)/base_link">
      <visual>
        <geometry>
          <box size="${payload_length} ${payload_width} ${payload_height}" />
        </geometry>
        <origin xyz="0 0 ${payload_height/2}" />
      </visual>
    </link>
  
    <!-- Create payload target point -->
    <link name="$(arg robot_name)/target_link">
    </link>
    <!-- Set payload target position -->
    <joint name="$(arg robot_name)/target_position" type="fixed">
      <axis xyz="0 1 0" />
      <parent link="$(arg robot_name)/base_link" />
      <child link="$(arg robot_name)/target_link" />
      <origin xyz="0 0 ${payload_height/2}" /> <!-- Starting position -->
    </joint>
  
    <!-- Create payload aim point -->
    <link name="$(arg robot_name)/aim_link">
    </link>
    <!-- Create payload aim virtual prismatic joint -->
    <joint name="$(arg robot_name)/aim_joint" type="prismatic">
      <axis xyz="1 0 0" />
      <parent link="$(arg robot_name)/target_link" />
      <child link="$(arg robot_name)/aim_link" />
      <limit effort="1000.0" lower="0.0" upper="0.6" velocity="1000" /> <!-- Pretty sure does nothing -->
      <origin xyz="0 0 0" /> <!-- Starting position -->
    </joint>
  
  </robot>